"""empty message

Revision ID: 09439cf0a2f0
Revises: d534d0559a2f
Create Date: 2022-02-09 14:18:26.644315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09439cf0a2f0'
down_revision = 'd534d0559a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
